url: "https://frouk3.github.io"
baseurl: ""
permalink: /index.html
theme: jekyll-theme-minimal
title: Frouk's Blog
description: A blog about tech, programming, and about Frouk's life.
timezone: Europe/Kyiv
theme_settings:
  post_navigation: true